### ISSUE TITLE
Docker run HABApp as not root

### ISSUE THREAD

**Issue by DerOetzi** [spacemanspiff2007/HABApp#259]
For security reasons the recommendation is to run services inside container without root users.

I can do a PR suggestion this weekend.

**Comment by spacemanspiff2007** [comment]
That would be very nice! Thank you for your help.

**Comment by DerOetzi** [comment]
@spacemanspiff2007 Can I support you somehow to get the release done? I'm really want to change to HABApp but need the slim-buster baseimage version to install signal-cli additional.

**Comment by spacemanspiff2007** [comment]
Can't you just create the docker image locally - as you did for testing?
Use the code from the master branch and then update[map_items](https://github.com/spacemanspiff2007/HABApp/blob/Develop/src/HABApp/openhab/map_items.py) to support the [call_item](https://github.com/spacemanspiff2007/HABApp/blob/Develop/src/HABApp/openhab/items/call_item.py)

The new docker image is a breaking change because the folder mounts have changed and I'd like to group that together with the refactor I'm working on.

**Comment by spacemanspiff2007** [comment]
@DerOetzi 
I just tested the dev branch and it seems to complete the tests without errors.
While that doesn't mean anything, you can try and use it (if you are adventurous)
