### ISSUE TITLE
Set correct version

### ISSUE THREAD

**Issue by nobbi1991** [spacemanspiff2007/HABApp#404]
Hi @spacemanspiff2007 

please set the next version to 1.2.0 since it adds new features :)

**Comment by spacemanspiff2007** [comment]
done

**Comment by nobbi1991** [comment]
Since you added interface / breaking changes the version must be 2.0.0 ;)

**Comment by spacemanspiff2007** [comment]
This project does not use semver - I'm using arbitrary version numbers.
So there is no need to change anything.

**Comment by nobbi1991** [comment]
OK, that's new for me.
Here you wrote, that you `try to do semantic versioning`: https://community.openhab.org/t/habapp-1-0/137627/39?u=nobbi123

What do you mean by arbitrary versioning?

**Comment by spacemanspiff2007** [comment]
That means I try to pick the version numbers so that they make somewhat sense but it's not strict semantic versioning.
Since HABApp is such a flexible application it's almost certain that any change breaks something for some user.
Obviously there is also a mismatch between what I consider the HABApp API and what e.g. you consider the HABApp API.
So what might be a non breaking change for me might be a breaking change for you because you use some part of the API that I did not intend to be used. The focus on version numbers thus creates a false sense of security.
It's intended to be just an identifier for a version that a user is using.

Since the version number seem to create more confusion than clarity I'm currently thinking about switching to CalVar to make it more clear.
