### ISSUE TITLE
Add option to wait for openhab before rule loading

### ISSUE THREAD

**Issue by andreasbrinch** [spacemanspiff2007/HABApp#86]
Openhab and habapp are running from docker containers and restarts themselves on reboot, but openhab is not ready when habapp is and does not start event listeners when it succesfully connects to openhab, so I need to restart habapp manually. I have attached the log from reboot and the log from the restart that makes it work.
[HABApp_reboot.log](https://github.com/spacemanspiff2007/HABApp/files/3774517/HABApp_reboot.log)
[HABApp_restart_that_works.log](https://github.com/spacemanspiff2007/HABApp/files/3774518/HABApp_restart_that_works.log)

**Comment by spacemanspiff2007** [comment]
I see the problem - I'll add a configurable wait time before the connection to openhab is established.

The problem is that you try to access an item which does not exist yet:
```
Loading file: /config/rules/bathroomswitch.py
Could not load /config/rules/bathroomswitch.py: Item SwitchZHC1_1 does not exist!!
HABApp.core.Items.ItemNotFoundException: Item SwitchZHC1_1 does not exist!
```

If you take a look at [the item docs](https://habapp.readthedocs.io/en/latest/rule.html#interacting-with-items) you can use the [class factories](https://habapp.readthedocs.io/en/latest/interface_openhab.html#HABApp.openhab.items.SwitchItem.get_create_item) which will create the item if it does not exist (class factories are the recommended way to interact with items):
````
from HABApp.openhab.items import SwitchItem
heater = SwitchItem.get_create_item('SwitchZHC1_1')
````

**Comment by andreasbrinch** [comment]
I actually chose get_item since I didn't want to create new items but connect to the ones defined in openhab and get an error if I misspelled something. If I do use get_create_item will it get linked to the item in openhab when it is ready? Also, I started experimenting with it and I get problems with the default initial_value of None. I can of course set it, but will it get updated with the actual value when openhab is ready? And will that trigger an event? In many rules I check on the state of items.

**Comment by spacemanspiff2007** [comment]
> If I do use get_create_item will it get linked to the item in openhab when it is ready?
> (...) but will it get updated with the actual value when openhab is ready?

Yes, since it has the same name it will refer to the same item and it will get updated. Everything will work as expected.
